y = int(input("what is your roll?"))
if y == 1:
    print("------")
    print("      ")
    print("  0   ")
    print("      ")
    print("------")
if y == 2:
    print("------")
    print("    0 ")
    print("      ")
    print(" 0    ")
    print("------")
if y == 3:
    print("------")
    print("  0   ")
    print("  0   ")
    print("  0   ")
    print("------")
if y == 4:
    print("------")
    print("0    0")
    print("      ")
    print("0    0")
    print("------")
if y == 5:
    print("------")
    print("0    0")
    print("  0   ")
    print("0    0")
    print("------")
if y == 6:
    print("------")
    print("0    0")
    print("0    0")
    print("0    0")
    print("------")
y = int(input("what is your roll?"))